name: 'LINE-in-action'
description: 'LINE notification for action'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'Pass your LINE-notify token here'
runs:
  using: 'node12'
  main: 'dist/index.js'
